# Generated by Django 3.2.8 on 2021-10-26 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_adhaar_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='user',
            name='l_name',
            field=models.CharField(default=datetime.date, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.date, max_length=20),
            preserve_default=False,
        ),
    ]
